### ISSUE TITLE
Emojis show up as characters in chat

### ISSUE THREAD

**Issue by plopilpy** [unnamed/emojis#14]
When typing emojis in chat, I can't see them. They show up as their respective characters.
My friends **can** see them. This issue doesn't happen when server resource packs are disabled, although my friends have the same resource packs and still see the emojis in chat.
Below is a screenshot:
https://i.imgur.com/uk62f6h.png

**Comment by yusshu** [comment]
Sorry for the late answer, please re-open the issue and provide some steps to reproduce this bug, if you still need help.
