### ISSUE TITLE
Rename project to "glyphs"

### ISSUE THREAD

**Issue by yusshu** [unnamed/emojis#3]
Emojis are the main feature of this plugin, however, it is possible to do more than just emojis; such as images for the tab, scoreboard, chat, titles, actionbars, etc... All this is possible using Placeholder API *(Because we hook on it)*

This is why I propose a name change, from "emojis" to "glyphs", which would make more sense and explain more the capability of this plugin

**Comment by FixedDev** [comment]
I agree with you, but, why glyphs? There's not a better name? lol

**Comment by yusshu** [comment]
Any suggestions?

**Comment by OcZi** [comment]
> Any suggestions?

something like text to image maybe

**Comment by yusshu** [comment]
- glyphs
- imagine
- imaging

**Comment by SrBedrock** [comment]
- surface

![Screenshot_20211207-133356~2](https://user-images.githubusercontent.com/51332006/145068963-47c91ec0-8e33-449c-aade-f02b0703937b.png)

**Comment by SrBedrock** [comment]
> I agree with you, but, why glyphs? There's not a better name? lol

glyphs seems to be a good name, distinct from other plugins and consistent with the plugin's function.

![Screenshot_20211208-123821~2](https://user-images.githubusercontent.com/51332006/145237502-93d49f0d-e2b8-4e78-a776-b51330f6c88f.png)

**Comment by pixeldev** [comment]
I totally agree with you, let's wait and see the responses of them
